name = "demo-db-test-worker"
main = "src/index.js"
compatibility_date = "2026-03-30"

[[d1_databases]]
binding = "DB"
database_name = "demo-db-test-db"
database_id = "0f4dca7c-ab4e-4ffb-88df-2e1692573f3a"